#!/usr/bin/env python3
"""
K.I.T. TradingView Pine Script Generator
Generate Pine Script v5 code from templates and descriptions
"""

import argparse
import json
from datetime import datetime
from typing import Optional, Dict, List

# Pine Script Templates

HEADER_TEMPLATE = '''// =====================================================
// Auto-generated by K.I.T. TradingView Script Generator
// Generated: {timestamp}
// =====================================================
//@version=5
'''

INDICATOR_TEMPLATES = {
    'rsi': '''
indicator("{name}", overlay=false)

// Inputs
length = input.int({length}, "RSI Length", minval=1)
overbought = input.int({overbought}, "Overbought Level")
oversold = input.int({oversold}, "Oversold Level")

// Calculation
rsiValue = ta.rsi(close, length)

// Plot
plot(rsiValue, "RSI", color.purple, linewidth=2)
hline(overbought, "Overbought", color.red, linestyle=hline.style_dashed)
hline(oversold, "Oversold", color.green, linestyle=hline.style_dashed)
hline(50, "Middle", color.gray, linestyle=hline.style_dotted)

// Background color
bgcolor(rsiValue > overbought ? color.new(color.red, 90) : rsiValue < oversold ? color.new(color.green, 90) : na)

// Alerts
alertcondition(ta.crossover(rsiValue, oversold), "RSI Oversold Cross", '{{"signal":"buy","indicator":"RSI","value":"' + str.tostring(rsiValue, "#.##") + '","ticker":"{{{{ticker}}}}"}}')
alertcondition(ta.crossunder(rsiValue, overbought), "RSI Overbought Cross", '{{"signal":"sell","indicator":"RSI","value":"' + str.tostring(rsiValue, "#.##") + '","ticker":"{{{{ticker}}}}"}}')
''',

    'macd': '''
indicator("{name}", overlay=false)

// Inputs
fastLength = input.int({fast_length}, "Fast Length")
slowLength = input.int({slow_length}, "Slow Length")
signalLength = input.int({signal_length}, "Signal Length")

// Calculations
[macdLine, signalLine, histLine] = ta.macd(close, fastLength, slowLength, signalLength)

// Plot
plot(macdLine, "MACD", color.blue, linewidth=2)
plot(signalLine, "Signal", color.orange, linewidth=2)
plot(histLine, "Histogram", color=histLine >= 0 ? color.green : color.red, style=plot.style_histogram)
hline(0, "Zero", color.gray)

// Alerts
alertcondition(ta.crossover(macdLine, signalLine), "MACD Bullish Cross", '{{"signal":"buy","indicator":"MACD","ticker":"{{{{ticker}}}}"}}')
alertcondition(ta.crossunder(macdLine, signalLine), "MACD Bearish Cross", '{{"signal":"sell","indicator":"MACD","ticker":"{{{{ticker}}}}"}}')
''',

    'bollinger': '''
indicator("{name}", overlay=true)

// Inputs
length = input.int({length}, "Length")
mult = input.float({multiplier}, "Multiplier")
src = input.source(close, "Source")

// Calculations
[middle, upper, lower] = ta.bb(src, length, mult)

// Plot
plot(upper, "Upper Band", color.red, linewidth=2)
plot(middle, "Middle Band", color.gray)
plot(lower, "Lower Band", color.green, linewidth=2)
fill(plot(upper, display=display.none), plot(lower, display=display.none), color=color.new(color.purple, 95))

// Alerts
alertcondition(ta.crossunder(close, lower), "Price Below Lower Band", '{{"signal":"buy","indicator":"BB","ticker":"{{{{ticker}}}}"}}')
alertcondition(ta.crossover(close, upper), "Price Above Upper Band", '{{"signal":"sell","indicator":"BB","ticker":"{{{{ticker}}}}"}}')
''',

    'ema': '''
indicator("{name}", overlay=true)

// Inputs
length = input.int({length}, "EMA Length")
src = input.source(close, "Source")

// Calculation
emaValue = ta.ema(src, length)

// Plot
plot(emaValue, "EMA", color.blue, linewidth=2)

// Trend color
plotColor = close > emaValue ? color.green : color.red
plot(emaValue, "EMA Trend", plotColor, linewidth=2)

// Alerts
alertcondition(ta.crossover(close, emaValue), "Price Cross Above EMA", '{{"signal":"buy","indicator":"EMA","ticker":"{{{{ticker}}}}"}}')
alertcondition(ta.crossunder(close, emaValue), "Price Cross Below EMA", '{{"signal":"sell","indicator":"EMA","ticker":"{{{{ticker}}}}"}}')
'''
}

STRATEGY_TEMPLATE = '''
strategy("{name}", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value={position_size}, commission_type=strategy.commission.percent, commission_value=0.1)

// ============ Inputs ============
{inputs}

// ============ Indicators ============
{indicators}

// ============ Entry Conditions ============
longCondition = {long_condition}
shortCondition = {short_condition}

// ============ Risk Management ============
slPercent = input.float({sl_pct}, "Stop Loss %", minval=0.1) / 100
tpPercent = input.float({tp_pct}, "Take Profit %", minval=0.1) / 100

// ============ Execute Trades ============
if longCondition
    strategy.entry("Long", strategy.long)
    strategy.exit("Long Exit", "Long", profit=close * tpPercent / syminfo.mintick, loss=close * slPercent / syminfo.mintick)

if shortCondition
    strategy.entry("Short", strategy.short)
    strategy.exit("Short Exit", "Short", profit=close * tpPercent / syminfo.mintick, loss=close * slPercent / syminfo.mintick)

// ============ Plots ============
{plots}

plotshape(longCondition, "Long Signal", shape.triangleup, location.belowbar, color.green, size=size.small)
plotshape(shortCondition, "Short Signal", shape.triangledown, location.abovebar, color.red, size=size.small)

// ============ K.I.T. Webhook Alerts ============
alertcondition(longCondition, "K.I.T. Long Signal", '{{"action":"buy","ticker":"{{{{ticker}}}}","price":"{{{{close}}}}","strategy":"{name}"}}')
alertcondition(shortCondition, "K.I.T. Short Signal", '{{"action":"sell","ticker":"{{{{ticker}}}}","price":"{{{{close}}}}","strategy":"{name}"}}')
'''

class PineGenerator:
    """Generate Pine Script code from templates"""
    
    def __init__(self):
        self.timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    def generate_indicator(self, indicator_type: str, **kwargs) -> str:
        """Generate an indicator Pine Script"""
        if indicator_type not in INDICATOR_TEMPLATES:
            raise ValueError(f"Unknown indicator type: {indicator_type}")
        
        template = INDICATOR_TEMPLATES[indicator_type]
        header = HEADER_TEMPLATE.format(timestamp=self.timestamp)
        
        # Set defaults based on indicator type
        defaults = self._get_indicator_defaults(indicator_type)
        defaults.update(kwargs)
        
        try:
            script = template.format(**defaults)
            return header + script
        except KeyError as e:
            raise ValueError(f"Missing parameter for {indicator_type}: {e}")
    
    def _get_indicator_defaults(self, indicator_type: str) -> Dict:
        """Get default parameters for each indicator type"""
        defaults = {
            'rsi': {'name': 'RSI', 'length': 14, 'overbought': 70, 'oversold': 30},
            'macd': {'name': 'MACD', 'fast_length': 12, 'slow_length': 26, 'signal_length': 9},
            'bollinger': {'name': 'Bollinger Bands', 'length': 20, 'multiplier': 2.0},
            'ema': {'name': 'EMA', 'length': 20}
        }
        return defaults.get(indicator_type, {})
    
    def generate_strategy(self, name: str, indicators: List[str], 
                         long_condition: str, short_condition: str,
                         sl_pct: float = 2.0, tp_pct: float = 4.0,
                         position_size: int = 100) -> str:
        """Generate a strategy Pine Script"""
        header = HEADER_TEMPLATE.format(timestamp=self.timestamp)
        
        # Parse indicators and generate code
        inputs_code, indicators_code, plots_code = self._parse_indicators(indicators)
        
        script = STRATEGY_TEMPLATE.format(
            name=name,
            inputs=inputs_code,
            indicators=indicators_code,
            long_condition=long_condition,
            short_condition=short_condition,
            sl_pct=sl_pct,
            tp_pct=tp_pct,
            position_size=position_size,
            plots=plots_code
        )
        
        return header + script
    
    def _parse_indicators(self, indicators: List[str]) -> tuple:
        """Parse indicator definitions and generate code"""
        inputs = []
        calcs = []
        plots = []
        
        for ind in indicators:
            parts = ind.lower().split(':')
            ind_type = parts[0]
            length = int(parts[1]) if len(parts) > 1 else 20
            
            var_name = f"{ind_type}_{length}"
            
            if ind_type == 'ema':
                inputs.append(f'{var_name}_len = input.int({length}, "{ind_type.upper()} {length} Length")')
                calcs.append(f'{var_name} = ta.ema(close, {var_name}_len)')
                plots.append(f'plot({var_name}, "{ind_type.upper()} {length}", color.blue)')
            elif ind_type == 'sma':
                inputs.append(f'{var_name}_len = input.int({length}, "{ind_type.upper()} {length} Length")')
                calcs.append(f'{var_name} = ta.sma(close, {var_name}_len)')
                plots.append(f'plot({var_name}, "{ind_type.upper()} {length}", color.orange)')
            elif ind_type == 'rsi':
                inputs.append(f'{var_name}_len = input.int({length}, "RSI Length")')
                calcs.append(f'{var_name} = ta.rsi(close, {var_name}_len)')
        
        return '\n'.join(inputs), '\n'.join(calcs), '\n'.join(plots)
    
    def generate_from_description(self, description: str) -> str:
        """Generate Pine Script from natural language description (basic implementation)"""
        description = description.lower()
        
        # Simple pattern matching for common strategies
        if 'rsi' in description and ('oversold' in description or 'below 30' in description):
            return self.generate_indicator('rsi', name='RSI Signal')
        
        if 'bollinger' in description or 'bb' in description:
            return self.generate_indicator('bollinger', name='Bollinger Bands')
        
        if 'macd' in description and 'cross' in description:
            return self.generate_indicator('macd', name='MACD Crossover')
        
        if ('ma' in description or 'moving average' in description) and 'cross' in description:
            # MA Crossover strategy
            return self.generate_strategy(
                name='MA Crossover',
                indicators=['ema:9', 'ema:21'],
                long_condition='ta.crossover(ema_9, ema_21)',
                short_condition='ta.crossunder(ema_9, ema_21)'
            )
        
        # Default: simple EMA
        return self.generate_indicator('ema', name='EMA Indicator')


def main():
    parser = argparse.ArgumentParser(description='K.I.T. Pine Script Generator')
    subparsers = parser.add_subparsers(dest='command', help='Commands')
    
    # Indicator command
    ind_parser = subparsers.add_parser('indicator', help='Generate an indicator')
    ind_parser.add_argument('--type', '-t', required=True, choices=['rsi', 'macd', 'bollinger', 'ema'])
    ind_parser.add_argument('--name', '-n', default=None)
    ind_parser.add_argument('--length', '-l', type=int, default=14)
    ind_parser.add_argument('--overbought', type=int, default=70)
    ind_parser.add_argument('--oversold', type=int, default=30)
    ind_parser.add_argument('--multiplier', '-m', type=float, default=2.0)
    ind_parser.add_argument('--output', '-o', default=None, help='Output file')
    
    # Strategy command
    strat_parser = subparsers.add_parser('strategy', help='Generate a strategy')
    strat_parser.add_argument('--name', '-n', required=True)
    strat_parser.add_argument('--indicators', '-i', required=True, help='Comma-separated indicators (e.g., ema:9,ema:21)')
    strat_parser.add_argument('--entry', '-e', required=True, help='Entry condition')
    strat_parser.add_argument('--exit', '-x', required=True, help='Exit condition')
    strat_parser.add_argument('--sl-pct', type=float, default=2.0)
    strat_parser.add_argument('--tp-pct', type=float, default=4.0)
    strat_parser.add_argument('--output', '-o', default=None)
    
    # Describe command
    desc_parser = subparsers.add_parser('describe', help='Generate from description')
    desc_parser.add_argument('--prompt', '-p', required=True)
    desc_parser.add_argument('--output', '-o', default=None)
    
    args = parser.parse_args()
    
    generator = PineGenerator()
    
    if args.command == 'indicator':
        kwargs = {
            'name': args.name or args.type.upper(),
            'length': args.length,
            'overbought': args.overbought,
            'oversold': args.oversold,
            'multiplier': args.multiplier
        }
        if args.type == 'macd':
            kwargs['fast_length'] = 12
            kwargs['slow_length'] = 26
            kwargs['signal_length'] = 9
        
        script = generator.generate_indicator(args.type, **kwargs)
        
    elif args.command == 'strategy':
        indicators = args.indicators.split(',')
        script = generator.generate_strategy(
            name=args.name,
            indicators=indicators,
            long_condition=args.entry,
            short_condition=args.exit,
            sl_pct=args.sl_pct,
            tp_pct=args.tp_pct
        )
        
    elif args.command == 'describe':
        script = generator.generate_from_description(args.prompt)
        
    else:
        parser.print_help()
        return
    
    if args.output:
        with open(args.output, 'w') as f:
            f.write(script)
        print(f"✅ Script saved to {args.output}")
    else:
        print(script)


if __name__ == '__main__':
    main()
